### PR TITLE
Add two commands: num_clients and num_clients:<subname>

### PR DESCRIPTION
**Pull request by Adam7288**
Responses are provided over the command channel socket as well

### CODE REVIEW

**Comment by hyper-prog** [comment]
Hi Adam!
I am happy to see you working on this project.
I put some comment into your code.
Sorry for delays, I have lots of work recently.

**Comment by Adam7288** [comment]
Where can I find the comments?

**Comment by hyper-prog** [comment]
I put the comments into to codes of pull request. 
Just look into your commits here.

**Comment by Adam7288** [comment]
Cannot see any comments sorry

**Comment by hyper-prog** [comment]
I done the coding istead of tell what i'm think to do. I hope it will be
suit your needs.
Have a nice day!

Peter

On Monday, April 22, 2024, Adam7288 ***@***.***> wrote:
> Cannot see any comments sorry
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci3.googleusercontent.com/meips/ADKq_NbpLGzlCw-HgHhWwnov26l0tP7pnSz3B7XS0XPZ5c1di-FCvtNa4QZJLBTT5g-G6Bu0z7e4IYt1YrW60-vh9DizCQeM23vr1PRr-pQIfGwk4aJPkEK5wRI-G-rNlz6lRbGfNOsiAIZNOU9g2nZQuTNzBK0GSrBihPq4EiijUD3C738WwnWRnpsDfhbmNvTeUdZlv_tkwQc9IYGoh9zRqlQApz2PQoK7FqgMIyH8A0ydINphcCrX1q0=s0-d-e1-ft#https://github.com/notifications/beacon/AH45JEVTAROALIBI34I2ERDY6VFMDA5CNFSM6AAAAABGPYLPHSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTT3NBT4W.gif>Message
ID: ***@***.***>

**Pull request merged**
